[system]
	inhibit=0
[system.status]
	type='None'
	# options in this secion depend on type set above, example for trafficlight
	#red_pin=<red led pin>
	#amber_pin=<amber led pin>
	#green_pin=<green led pin>
	# example for RGB
	#base_pin=<red anode pin>
[network]
	ssid='<ssid>'
	key='<passphrase>'
[network.mqtt]
	id='node_1'
	server='oxin-ssdm.local'
	port=1883
[temp1]
	module='max31865_dc'
	addr=[6,5]
	ref_resistance=430
[enviro1]
	module='ens160_dc'
	bus=[0,1,0]
	dht_pin=14